Align filename to class name
We need to fix filename as well since pull request was merged [1],
otherwise we have error:

    obj = getattr(mod, pluginname)()
AttributeError: 'module' object has no attribute 'PlaybookExtention'

[1]. https://github.com/tsukinowasha/ansible-lint-rules/pull/8